### ISSUE TITLE
ubuntu installation problem - hdf5

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdatasimulator#39]
I am getting the following error trying to install the package on linux/ubuntu, today

After issue the command
python -m pip install -e .

in the lvmdatasimulator director

ERROR: Could not find a version that satisfies the requirement hdf5 (from sdss-lvmdatasimulator==0.9.0) (from versions: none)
ERROR: No matching distribution found for hdf5 (from sdss-lvmdatasimulator==0.9.0)

Can you tell me what exactly are you trying to import.   In the version that I installed a few weeks ago (on my Mac), the setup.cfg file does not have, but it is obvious, looking at the history,  this is a recent addition

commit 6cda41a8d00e355a00ad5d69b7b89232a75beb0b (HEAD -> main, origin/main, origin/HEAD)
Author: cloud182 <enry91con@gmail.com>
Date:   Wed Jun 15 09:30:25 2022 -0400

    including fiber id in reg file

commit 16cf92a526040b97de295fb5282c6dcf5193dee7
Author: cloud182 <enry91con@gmail.com>
Date:   Thu Jun 9 15:10:00 2022 -0400

    adding hdf5 to the install requirements

If I go back to the commit that is just before this, I have no installation problem.

**Comment by cloud182** [comment]
This error should be fixed now. 

We got a report that on the M1 Mac hdf5 is a package that needs to be imported to make some of the dependencies of the simulator to work. In an attempt to fix this issue we included hdf5 as a requirement for lvmdatasimulator. 

While this seems to work on the M1 Macs, hdf5 apparently is not on pip for other systems. We decided, therefore, to go back to a previous state, removing hdf5 from the requirements, but we included a note on the README about this problem. If you download the simulator again this problem should be fixed and you will get some other updates.
