### ISSUE TITLE
Problem with Tutorial #3

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdatasimulator#48]
The last major step in tutorial 3 is failing because it is not finding the fits files that were created earlier.  

A quick fix is as follows, but it's probably not what one would like

```
print(name)
print(f"{name}_6550_6570_input_map.fits")
x=name+'/'
print(x)
fig = plt.figure(figsize=(18, 14))
with fits.open(x+f"{name}_6550_6570_input_map.fits") as hdu:
    ha_input = hdu[0].data
with fits.open(x+f"{name}_6715_6732_input_map.fits") as hdu:
    s2_input = hdu[0].data
with fits.open(x+f"{name}_5000_5010_input_map.fits") as hdu:
    o3_input = hdu[0].data
with fits.open(x+f"{name}_4855_4865_input_map.fits") as hdu:
    hb_input = hdu[0].data
```

The rest of the code seems fine.

**Comment by cloud182** [comment]
Hi, thanks for pointing this out. We just missed that piece of code when updating the tutorial to match the new naming convention. 
Now everything should work.

Enrico
